name: Scheduled CI workflow

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    inputs:
      # å¯ä»¥å®šä¹‰ä¸€äº›è¾“å…¥å‚æ•°
      message:
        description: 'Message from the trigger'
        required: false

jobs:
  run-ci-workflow:
    name: Run CI workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run CI workflow
        permissions:
          contents: write # å…è®¸å†™å…¥æ–‡ä»¶
          actions: write # **å…³é”®**ï¼šå…è®¸è§¦å‘ actions
        run: |
          # è·å–å½“å‰æ—¥æœŸå’Œæ—¶é—´
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          COMMIT_MESSAGE="ğŸ• auto: $CURRENT_DATE"
          gh workflow run "CI" -f message="$COMMIT_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
