name: Scheduled Empty Commit

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch: # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  create-empty-commit:
    name: Create Empty Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create empty commit
        run: |
          # è·å–å½“å‰æ—¥æœŸå’Œæ—¶é—´
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          COMMIT_MESSAGE="ğŸ• auto: $CURRENT_DATE"

          # åˆ›å»ºä¸€ä¸ªç©ºçš„æäº¤
          git commit --allow-empty -m "$COMMIT_MESSAGE"

      - name: Push to repository
        run: |
          git push origin HEAD:${{ github.ref }}
